name: ctrl_finance_app
description: Aplicativo avançado de controle financeiro com foco em relatórios e gestão de dívidas/empréstimos.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
