name: Build and Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: cd flutter_app && flutter pub get
      - name: Build APK
        run: cd flutter_app && flutter build apk --release
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CtrlFinance-Release-APK
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
